# Generated by Django 5.2 on 2025-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='country',
            field=models.CharField(default='UK', max_length=100),
        ),
    ]
